name: network-monitoring-stack
services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:v3
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
        - "--config.file=/etc/prometheus/prometheus.yml"
        - '--web.enable-admin-api'
        - '--web.enable-remote-write-receiver'
        - '--web.enable-otlp-receiver'
        - '--enable-feature=exemplar-storage'
        - "--enable-feature=native-histograms"
    ports:
      - "9090:9090"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4318:4318"
    depends_on:
      - prometheus

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    ports:
      - "9115:9115"
    volumes:
      - ./config/blackbox.yml:/etc/blackbox_exporter/config.yml
    command:
      - "--config.file=/etc/blackbox_exporter/config.yml"
    depends_on:
      - prometheus


volumes:
  grafana_data: