name: CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*.*.*'
  pull_request:

jobs:
  test-and-lint:
    name: Tests & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: https://code.forgejo.org/actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Installation de Go
        uses: https://code.forgejo.org/actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Vérification du code (go vet)
        run: go vet ./...

      - name: Tests unitaires avec Race Detector
        run: go test ./... -v -race -cover

      - name: Linter golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=5m

      - name: Validation du build GoReleaser (Snapshot)
        uses: https://github.com/goreleaser/goreleaser-action@v7
        with:
          distribution: goreleaser
          version: "~> v2"
          args: build --snapshot --clean
