name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release-binaries:
    name: Release Binaries & Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: https://code.forgejo.org/actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Installation de Go
        uses: https://code.forgejo.org/actions/setup-go@v7
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Run GoReleaser
        uses: https://github.com/goreleaser/goreleaser-action@v7
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GORELEASER_FORCE_TOKEN: gitea
          GITEA_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITEA_URL: "https://git.omniumcorp.fr"
